In [152]:
import numpy as np
import pandas as pd
import sklearn.datasets
import sklearn.feature_extraction.text

In [230]:
categories = ['alt.atheism', 'soc.religion.christian',
              'comp.graphics', 'sci.med']
twenty_train = sklearn.datasets.fetch_20newsgroups(subset='train',
    categories=categories, shuffle=True, random_state=42)

line_ind = 0
line = twenty_train.data[line_ind]
print(line)

count_vect = sklearn.feature_extraction.text.CountVectorizer()

X_train_counts = count_vect.fit_transform(twenty_train.data)

line_countvectorized = X_train_counts.toarray()[line_ind]

From: sd345@city.ac.uk (Michael Collier)
Subject: Converting images to HP LaserJet III?
Nntp-Posting-Host: hampton
Organization: The City University
Lines: 14

Does anyone know of a good way (standard PC application/PD utility) to
convert tif/img/tga files into LaserJet III format.  We would also like to
do the same, converting to HPGL (HP plotter) files.

Please email any response.

Is this the correct group?

Thanks in advance.  Michael.
--
Michael Collier (Programmer)                 The Computer Unit,
Email: M.P.Collier@uk.ac.city                The City University,
Tel: 071 477-8000 x3769                      London,
Fax: 071 477-8565                            EC1V 0HB.

In [252]:
ind_line_countvectorized_nonzero = np.where(line_countvectorized>0)[0]

In [253]:
ind_line_countvectorized_nonzero

array([  177,   230,   587,  2326,  3062,  3166,  4017,  4378,  4808,
        5195,  5201,  5285,  8696,  9031,  9338,  9801,  9805,  9932,
       12014, 12051, 12541, 12833, 14085, 14281, 14676, 14887, 15576,
       15837, 16082, 16881, 16916, 16927, 17302, 17366, 17389, 17556,
       18268, 18474, 19458, 19780, 20198, 20253, 20459, 21661, 23122,
       23610, 23915, 24651, 24677, 25337, 25361, 25663, 26175, 27836,
       28619, 29022, 30623, 31077, 31915, 32116, 32135, 32142, 32270,
       32391, 32493, 33256, 33572, 33597, 33915, 34755, 34775, 35312, 35416])

In [254]:
type(ind_line_countvectorized_nonzero)

numpy.ndarray

In [238]:
count_vect.get_feature_names()[33597]

'university'

In [256]:
words = np.array(count_vect.get_feature_names())[ind_line_countvectorized_nonzero]

In [244]:
words = [count_vect.get_feature_names()[i] for i in ind_line_countvectorized_nonzero[0]]

['071',
 '0hb',
 '14',
 '477',
 '8000',
 '8565',
 'ac',
 'advance',
 'also',
 'any',
 'anyone',
 'application',
 'city',
 'collier',
 'computer',
 'convert',
 'converting',
 'correct',
 'do',
 'does',
 'ec1v',
 'email',
 'fax',
 'files',
 'format',
 'from',
 'good',
 'group',
 'hampton',
 'host',
 'hp',
 'hpgl',
 'iii',
 'images',
 'img',
 'in',
 'into',
 'is',
 'know',
 'laserjet',
 'like',
 'lines',
 'london',
 'michael',
 'nntp',
 'of',
 'organization',
 'pc',
 'pd',
 'please',
 'plotter',
 'posting',
 'programmer',
 'response',
 'same',
 'sd345',
 'standard',
 'subject',
 'tel',
 'tga',
 'thanks',
 'the',
 'this',
 'tif',
 'to',
 'uk',
 'unit',
 'university',
 'utility',
 'way',
 'we',
 'would',
 'x3769']

In [260]:
tf_transformer = sklearn.feature_extraction.text.TfidfTransformer(use_idf=False)
X_train_tf = tf_transformer.fit_transform(X_train_counts)

line_tf = X_train_tf.toarray()[line_ind]

tfidf_transformer = sklearn.feature_extraction.text.TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

line_tfidf = X_train_tfidf.toarray()[line_ind]

In [246]:
line_tf[ind_line_countvectorized_nonzero]

array([ 0.15075567,  0.07537784,  0.07537784,  0.15075567,  0.07537784,
        0.07537784,  0.15075567,  0.07537784,  0.07537784,  0.07537784,
        0.07537784,  0.07537784,  0.30151134,  0.22613351,  0.07537784,
        0.07537784,  0.15075567,  0.07537784,  0.07537784,  0.07537784,
        0.07537784,  0.15075567,  0.07537784,  0.15075567,  0.07537784,
        0.07537784,  0.07537784,  0.07537784,  0.07537784,  0.07537784,
        0.15075567,  0.07537784,  0.15075567,  0.07537784,  0.07537784,
        0.07537784,  0.07537784,  0.07537784,  0.07537784,  0.15075567,
        0.07537784,  0.07537784,  0.07537784,  0.22613351,  0.07537784,
        0.07537784,  0.07537784,  0.07537784,  0.07537784,  0.07537784,
        0.07537784,  0.07537784,  0.07537784,  0.07537784,  0.07537784,
        0.07537784,  0.07537784,  0.07537784,  0.07537784,  0.07537784,
        0.07537784,  0.37688918,  0.07537784,  0.07537784,  0.30151134,
        0.15075567,  0.07537784,  0.15075567,  0.07537784,  0.07537784,
        0.07537784,  0.07537784,  0.07537784])

In [273]:
df_text_features = pd.DataFrame({
    'ind': ind_line_countvectorized_nonzero,
    'word': words,
    'count': line_countvectorized[ind_line_countvectorized_nonzero],
    'tf': line_tf[ind_line_countvectorized_nonzero],
    'tfidf': line_tfidf[ind_line_countvectorized_nonzero],
})

In [275]:
df_text_features

    count    ind        tf     tfidf          word
0       2    177  0.150756  0.256120           071
1       1    230  0.075378  0.134871           0hb
2       1    587  0.075378  0.059662            14
3       2   2326  0.150756  0.246455           477
4       1   3062  0.075378  0.107836          8000
5       1   3166  0.075378  0.134871          8565
6       2   4017  0.150756  0.124918            ac
7       1   4378  0.075378  0.068661       advance
8       1   4808  0.075378  0.039004          also
9       1   5195  0.075378  0.031095           any
10      1   5201  0.075378  0.043162        anyone
11      1   5285  0.075378  0.084135   application
12      4   8696  0.301511  0.314400          city
13      3   9031  0.226134  0.384180       collier
14      1   9338  0.075378  0.049672      computer
15      1   9801  0.075378  0.078308       convert
16      2   9805  0.150756  0.215672    converting
17      1   9932  0.075378  0.063506       correct
18      1  12014  0.075378  0.031043            do
19      1  12051  0.075378  0.037793          does
20      1  12541  0.075378  0.134871          ec1v
21      2  12833  0.150756  0.125601         email
22      1  14085  0.075378  0.066665           fax
23      2  14281  0.150756  0.136358         files
24      1  14676  0.075378  0.076919        format
25      1  14887  0.075378  0.016798          from
26      1  15576  0.075378  0.042704          good
27      1  15837  0.075378  0.054174         group
28      1  16082  0.075378  0.113827       hampton
29      1  16881  0.075378  0.036044          host
..    ...    ...       ...       ...           ...
43      3  21661  0.226134  0.196228       michael
44      1  23122  0.075378  0.036375          nntp
45      1  23610  0.075378  0.018250            of
46      1  23915  0.075378  0.017762  organization
47      1  24651  0.075378  0.078021            pc
48      1  24677  0.075378  0.097963            pd
49      1  25337  0.075378  0.049359        please
50      1  25361  0.075378  0.119479       plotter
51      1  25663  0.075378  0.034291       posting
52      1  26175  0.075378  0.084975    programmer
53      1  27836  0.075378  0.068991      response
54      1  28619  0.075378  0.047272          same
55      1  29022  0.075378  0.134871         sd345
56      1  30623  0.075378  0.068661      standard
57      1  31077  0.075378  0.016798       subject
58      1  31915  0.075378  0.086319           tel
59      1  32116  0.075378  0.102184           tga
60      1  32135  0.075378  0.049102        thanks
61      5  32142  0.376889  0.088654           the
62      1  32270  0.075378  0.023871          this
63      1  32391  0.075378  0.128060           tif
64      4  32493  0.301511  0.072838            to
65      2  33256  0.150756  0.118197            uk
66      1  33572  0.075378  0.093130          unit
67      2  33597  0.150756  0.065676    university
68      1  33915  0.075378  0.099941       utility
69      1  34755  0.075378  0.043342           way
70      1  34775  0.075378  0.034481            we
71      1  35312  0.075378  0.031270         would
72      1  35416  0.075378  0.134871         x3769

[73 rows x 5 columns]